export const SET_ALL_BRANDS = "SET_ALL_BRANDS";
export const FOLD_CURRENT_BRAND_GROUP = "FOLD_CURRENT_BRAND_GROUP";
export const SEARCH_BRANDS = "SEARCH_BRANDS";
export const REVERSE_BRANDS_SORT = "REVERSE_BRANDS_SORT";

export const DELETE_BRANDS = "DELETE_BRANDS";
export const ADD_NEW_BRAND = "ADD_NEW_BRAND";
