export const SET_OUTPUT_BRANDS = "SET_OUTPUT_BRANDS";

export const SET_ALL_BRANDS = "SET_ALL_BRANDS";
export const CHANGE_SORT_TYPE = "CHANGE_SORT_TYPE";
export const FOLD_CURRENT_BRAND_GROUP = "FOLD_CURRENT_BRAND_GROUP";
export const FIND_BRAND = "FIND_BRAND";
